apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - metadata
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: metadata
        image: gcr.io/dcsc2024-437804/metadata-service-image:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 200
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 200
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: service-account-key
          mountPath: /app/wikipedia-service-account-key.json
          subPath: wikipedia-service-account-key.json
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/wikipedia-service-account-key.json
      volumes:
      - name: service-account-key
        secret:
          secretName: bigquery-service-account-secret
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
spec:
  type: ClusterIP
  selector:
    app: metadata
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metadata-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metadata-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50